- name: composer
  src: geerlingguy.composer
  version: 1.5.0

- name: ntp
  src: resmo.ntp
  version: 0.4.0

- name: logrotate
  src: nickhammond.logrotate
  version: 3c627cb

- name: swapfile
  src: kamaln7.swapfile
  version: 0.4

- src: geerlingguy.daemonize
  version: 1.1.1

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.0.0
